In [1]:
import math
import numpy as np

In [2]:
0.8/math.sqrt(2)

0.565685424949238

In [3]:
state_1 = np.array([0.8, 0.6])
state_2 = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)]) 
print(state_1)
print(state_2)

[0.8 0.6]
[0.70710678+0.j         0.        +0.70710678j]


In [4]:
np.dot(np.conj(state_2),state_1)

(0.565685424949238-0.42426406871192845j)

In [5]:
np.dot(np.conj(state_1),state_2)

(0.565685424949238+0.42426406871192845j)

In [6]:
print(state_2)
print(np.conj(state_2))
print(np.conjugate(state_2))

[0.70710678+0.j         0.        +0.70710678j]
[0.70710678-0.j         0.        -0.70710678j]
[0.70710678-0.j         0.        -0.70710678j]


In [7]:
State = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)])
def measure_state(state, num_meas=10):
    x_prob = state[0] * np.conj(state[0])
    x_prob = x_prob.real
    y_prob = state[1] * np.conj(state[1])
    y_prob = y_prob.real
    choice_ = [0,1]
    arr = np.random.choice(choice_,num_meas,p=[x_prob,y_prob])
    return arr
measure_state(State)

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1])

In [8]:
np.square(0.8) + np.square(0.6)

1.0

In [9]:
1j * 1j

(-1+0j)

In [10]:
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])
H = [[1/np.sqrt(2),1/np.sqrt(2)],
                 [1/np.sqrt(2),-1/np.sqrt(2)]]

T = [[1,0],[0,np.exp(1j * np.pi/4)]]
S = [[1,0],[0,-1]]
Z = [[1,0],[0,-1]]
Y = [[0,-1j],[1j,0]]
X = [[0,1],[1,0]]


In [11]:
H_T = np.matmul(T,H)
H_T_S = np.matmul(S,H_T)
H_S_T_H = np.matmul(H,H_T_S)
ans = np.matmul(H_S_T_H,ket_0)
print(ans)

[0.14644661-0.35355339j 0.85355339+0.35355339j]


In [12]:
np.matmul(np.matmul(H,X),H)

array([[ 1.,  0.],
       [ 0., -1.]])

In [13]:
np.matmul(np.matmul(X,Y),ket_0) == 1j * np.matmul(Z,ket_0)

array([ True,  True])

In [14]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def initialize_state():
    """Prepare a qubit in state |0>.
    
    Returns:
        array[float]: the vector representation of state |0>.
    """

    ##################
    # YOUR CODE HERE #
    ##################
    ket_0 = np.array([1,0])
    
    ket_1 = np.array([0,1])
    return ket_0

In [16]:
def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)

In [17]:
def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome

In [18]:
def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.
    
    Try and do so using three lines of code or less!
    
    Returns:
        array[int]: the measurement results after running the algorithm 100 times
    """
    
    ##################
    # YOUR CODE HERE #
    new_state = apply_u(initialize_state())
    measure_state_temp = measure_state(new_state,100)
    return(measure_state_temp)
    ##################

    # PREPARE THE STATE, APPLY U, THEN TAKE 100 MEASUREMENT SAMPLES
    pass

In [19]:
quantum_algorithm()

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0])

In [20]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def initialize_state():
    """Prepare a qubit in state |0>.
    
    Returns:
        array[float]: the vector representation of state |0>.
    """

    ##################
    # YOUR CODE HERE #
    ##################
    ket_0 = np.array([1,0])
    ket_1 = np.array(0,1)
    return ket_0

    # PREPARE THE STATE |0>   
    pass


def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)


def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome


def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.
    
    Try and do so using three lines of code or less!
    
    Returns:
        array[int]: the measurement results after running the algorithm 100 times
    """
    
    ##################
    # YOUR CODE HERE #
    new_state = apply_u(initialize_state())
    measure_state_temp = measure_state(new_state,100)
    return(measure_state_temp)
    ##################

    # PREPARE THE STATE, APPLY U, THEN TAKE 100 MEASUREMENT SAMPLES
    pass


In [21]:
quantum_algorithm()

TypeError: Cannot interpret '1' as a data type