In [7]:
import math
import numpy as np

In [8]:
0.8/math.sqrt(2)

0.565685424949238

In [18]:
state_1 = np.array([0.8, 0.6])
state_2 = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)]) 
print(state_1)
print(state_2)

[0.8 0.6]
[0.70710678+0.j         0.        +0.70710678j]


In [10]:
np.dot(np.conj(state_2),state_1)

(0.565685424949238-0.42426406871192845j)

In [11]:
np.dot(np.conj(state_1),state_2)

(0.565685424949238+0.42426406871192845j)

In [20]:
print(state_2)
print(np.conj(state_2))
print(np.conjugate(state_2))

[0.70710678+0.j         0.        +0.70710678j]
[0.70710678-0.j         0.        -0.70710678j]
[0.70710678-0.j         0.        -0.70710678j]


In [47]:
State = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)])
def measure_state(state, num_meas=10):
    x_prob = state[0] * np.conj(state[0])
    x_prob = x_prob.real
    y_prob = state[1] * np.conj(state[1])
    y_prob = y_prob.real
    choice_ = [0,1]
    arr = np.random.choice(choice_,num_meas,p=[x_prob,y_prob])
    return arr
measure_state(State)

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 0])

In [31]:
np.square(0.8) + np.square(0.6)

1.0

In [29]:
1j * 1j

(-1+0j)

In [79]:
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])
H = [[1/np.sqrt(2),1/np.sqrt(2)],
                 [1/np.sqrt(2),-1/np.sqrt(2)]]

T = [[1,0],[0,np.exp(1j * np.pi/4)]]
S = [[1,0],[0,-1]]
Z = [[1,0],[0,-1]]
Y = [[0,-1j],[1j,0]]
X = [[0,1],[1,0]]


In [88]:
H_T = np.matmul(T,H)
H_T_S = np.matmul(S,H_T)
H_S_T_H = np.matmul(H,H_T_S)
ans = np.matmul(H_S_T_H,ket_0)
print(ans)

[0.14644661-0.35355339j 0.85355339+0.35355339j]


In [90]:
np.matmul(np.matmul(H,X),H)

array([[ 1.,  0.],
       [ 0., -1.]])

In [92]:
np.matmul(np.matmul(X,Y),ket_0) == 1j * np.matmul(Z,ket_0)

array([ True,  True])