In [1]:
import math
import numpy as np

In [2]:
0.8/math.sqrt(2)

0.565685424949238

In [3]:
state_1 = np.array([0.8, 0.6])
state_2 = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)]) 
print(state_1)
print(state_2)

[0.8 0.6]
[0.70710678+0.j         0.        +0.70710678j]


In [4]:
np.dot(np.conj(state_2),state_1)

(0.565685424949238-0.42426406871192845j)

In [5]:
np.dot(np.conj(state_1),state_2)

(0.565685424949238+0.42426406871192845j)

In [6]:
print(state_2)
print(np.conj(state_2))
print(np.conjugate(state_2))

[0.70710678+0.j         0.        +0.70710678j]
[0.70710678-0.j         0.        -0.70710678j]
[0.70710678-0.j         0.        -0.70710678j]


In [7]:
State = np.array([1 / np.sqrt(2), 1j / np.sqrt(2)])
def measure_state(state, num_meas=10):
    x_prob = state[0] * np.conj(state[0])
    x_prob = x_prob.real
    y_prob = state[1] * np.conj(state[1])
    y_prob = y_prob.real
    choice_ = [0,1]
    arr = np.random.choice(choice_,num_meas,p=[x_prob,y_prob])
    return arr
measure_state(State)

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 0])

In [8]:
np.square(0.8) + np.square(0.6)

1.0

In [9]:
1j * 1j

(-1+0j)

In [10]:
ket_0 = np.array([1, 0])
ket_1 = np.array([0, 1])
H = [[1/np.sqrt(2),1/np.sqrt(2)],
                 [1/np.sqrt(2),-1/np.sqrt(2)]]

T = [[1,0],[0,np.exp(1j * np.pi/4)]]
S = [[1,0],[0,-1]]
Z = [[1,0],[0,-1]]
Y = [[0,-1j],[1j,0]]
X = [[0,1],[1,0]]


In [11]:
H_T = np.matmul(T,H)
H_T_S = np.matmul(S,H_T)
H_S_T_H = np.matmul(H,H_T_S)
ans = np.matmul(H_S_T_H,ket_0)
print(ans)

[0.14644661-0.35355339j 0.85355339+0.35355339j]


In [12]:
np.matmul(np.matmul(H,X),H)

array([[ 1.00000000e+00, -2.23711432e-17],
       [ 2.23711432e-17, -1.00000000e+00]])

In [13]:
np.matmul(np.matmul(X,Y),ket_0) == 1j * np.matmul(Z,ket_0)

array([ True,  True])

In [14]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def initialize_state():
    """Prepare a qubit in state |0>.
    
    Returns:
        array[float]: the vector representation of state |0>.
    """

    ##################
    # YOUR CODE HERE #
    ##################
    ket_0 = np.array([1,0])
    
    ket_1 = np.array([0,1])
    return ket_0

In [15]:
def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)

In [16]:
def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome

In [17]:
def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.
    
    Try and do so using three lines of code or less!
    
    Returns:
        array[int]: the measurement results after running the algorithm 100 times
    """
    
    ##################
    # YOUR CODE HERE #
    new_state = apply_u(initialize_state())
    measure_state_temp = measure_state(new_state,100)
    return(measure_state_temp)
    ##################

    # PREPARE THE STATE, APPLY U, THEN TAKE 100 MEASUREMENT SAMPLES
    pass

In [18]:
quantum_algorithm()

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0])

In [19]:
U = np.array([[1, 1], [1, -1]]) / np.sqrt(2)

def initialize_state():
    """Prepare a qubit in state |0>.
    
    Returns:
        array[float]: the vector representation of state |0>.
    """

    ##################
    # YOUR CODE HERE #
    ##################
    ket_0 = np.array([1,0])
    ket_1 = np.array([0,1])
    return ket_0

    # PREPARE THE STATE |0>   
    pass


def apply_u(state):
    """Apply a quantum operation."""
    return np.dot(U, state)


def measure_state(state, num_meas):
    """Measure a quantum state num_meas times."""
    p_alpha = np.abs(state[0]) ** 2
    p_beta = np.abs(state[1]) ** 2
    meas_outcome = np.random.choice([0, 1], p=[p_alpha, p_beta], size=num_meas)
    return meas_outcome


def quantum_algorithm():
    """Use the functions above to implement the quantum algorithm described above.
    
    Try and do so using three lines of code or less!
    
    Returns:
        array[int]: the measurement results after running the algorithm 100 times
    """
    
    ##################
    # YOUR CODE HERE #
    new_state = apply_u(initialize_state())
    measure_state_temp = measure_state(new_state,100)
    return(measure_state_temp)
    ##################

    # PREPARE THE STATE, APPLY U, THEN TAKE 100 MEASUREMENT SAMPLES
    pass


In [20]:
quantum_algorithm()

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [21]:
import pennylane as qml

def my_circuit(theta, phi): 
    ##################
    # YOUR CODE HERE #
    ##################

    # REORDER THESE 5 GATES TO MATCH THE CIRCUIT IN THE PICTURE

    qml.CNOT(wires=[0, 1])
    qml.RX(theta, wires=2)
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[2, 0])
    qml.RY(phi, wires=1)
    # This is the measurement; we return the probabilities of all possible output states
    # You'll learn more about what types of measurements are available in a later node
    return qml.probs(wires=[0, 1, 2])
my_circuit(90,180)

probs(wires=[0, 1, 2])

In [22]:
#To run any quantum 
dev = qml.device('default.qubit', wires=['wire_a','wire_b'])


## Creating QNode

In [23]:
# This creates a device with three wires on which PennyLane can run computations
dev = qml.device("default.qubit", wires=3)


def my_circuit(theta, phi, omega):

    ##################
    # YOUR CODE HERE #
    qml.RX(theta,wires=0)
    qml.RY(phi,wires=1)
    qml.RZ(omega,wires=2)
    qml.CNOT(wires=[0,1])
    qml.CNOT(wires=[1,2])
    qml.CNOT(wires=[2,0])
    ##################

    # IMPLEMENT THE CIRCUIT BY ADDING THE GATES

    # Here are two examples, so you can see the format:
    # qml.CNOT(wires=[0, 1])
    # qml.RX(theta, wires=0)
    



    return qml.probs(wires=[0, 1, 2])


# This creates a QNode, binding the function and device
my_qnode = qml.QNode(my_circuit, dev)

# We set up some values for the input parameters
theta, phi, omega = 0.1, 0.2, 0.3

# Now we can execute the QNode by calling it like we would a regular function
my_qnode(theta, phi, omega)


tensor([9.87560268e-01, 0.00000000e+00, 0.00000000e+00, 2.47302134e-03,
        2.48960206e-05, 0.00000000e+00, 0.00000000e+00, 9.94181506e-03], requires_grad=True)

In [46]:
U = np.array([[1,1],[1,-1]])/np.sqrt(2)
dev = qml.device("default.qubit",wires = 1)

@qml.qnode(dev)
def varied_initial_state(state):
    psi = ket_0
    if state == 1:
        qml.PauliX(wires = 0)
    qml.QubitUnitary(U,wires=0)
    return qml.state()
# This creates a QNode, binding the function and device
print(varied_initial_state(1))
print(varied_initial_state(0))

[ 0.70710678+0.j -0.70710678+0.j]
[0.70710678+0.j 0.70710678+0.j]


In [47]:
@qml.qnode(dev)
def apply_hadamard():
    qml.Hadamard(wires=0)
    return qml.state()
apply_hadamard()

tensor([0.70710678+0.j, 0.70710678+0.j], requires_grad=True)

In [49]:
# Apply Hadamard to a state
@qml.qnode(dev)
def hadamard(state):
    psi = ket_0
    if state == 1:
        qml.PauliX(wires = 0)
    qml.Hadamard(wires=0)
    return qml.state()
print("The Hadamard 0 is: {} and the Hadamard 1 is: {}".format(hadamard(0),hadamard(1)))


The Hadamard 0 is: [0.70710678+0.j 0.70710678+0.j] and the Hadamard 1 is: [ 0.70710678+0.j -0.70710678+0.j]


In [50]:
dev = qml.device("default.qubit",wires  = 1)
@qml.qnode(dev)
def apply_hxh(state):
    if state == 1:
        qml.PauliX(wires = 0)
    qml.Hadamard(wires = 0)
    qml.PauliX(wires = 0)
    qml.Hadamard(wires = 0)
    return qml.state()
print(apply_hxh(0))
print(apply_hxh(1))

[1.+0.j 0.+0.j]
[ 0.+0.j -1.+0.j]
