In [1]:
import pennylane as qml
from pennylane import numpy as np

In [2]:
Hadamard_gate = 1/np.sqrt(2) * np.asarray([[1,1],[1,-1]])
eigen_val_H,eigen_vec_H = np.linalg.eigh(Hadamard_gate)
print(f"The eigenvalue of Hadamarad gates are: {eigen_val_H}")
print(f" THe eigenVec of Hadamard gates are: {eigen_vec_H}")

The eigenvalue of Hadamarad gates are: [-1.  1.]
 THe eigenVec of Hadamard gates are: [[ 0.38268343 -0.92387953]
 [-0.92387953 -0.38268343]]


In [4]:
# 1
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def apply_z_to_plus():
    """Write a circuit that applies PauliZ to the |+> state and returns
    the state.

    Returns:
        array[complex]: The state of the qubit after the operations.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # CREATE THE |+> STATE
    qml.Hadamard(wires = 0)

    # APPLY PAULI Z
    qml.PauliZ(wires = 0)

    # RETURN THE STATE
    return qml.state()

print(apply_z_to_plus())


[ 0.70710678+0.j -0.70710678+0.j]


In [5]:
# 2
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def fake_z():
    """Use RZ to produce the same action as Pauli Z on the |+> state.

    Returns:
        array[complex]: The state of the qubit after the operations.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # CREATE THE |+> STATE
    qml.Hadamard(wires = 0)

    # APPLY RZ
    qml.RZ(np.pi,wires = 0)

    # RETURN THE STATE
    return qml.state()
fake_z()

tensor([4.32978028e-17-0.70710678j, 4.32978028e-17+0.70710678j], requires_grad=True)

In [6]:
# 3
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def many_rotations():
    """Implement the circuit depicted above and return the quantum state.

    Returns:
        array[complex]: The state of the qubit after the operations.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # IMPLEMENT THE CIRCUIT

    # RETURN THE STATE
    qml.Hadamard(wires = 0)
    qml.S(wires = 0)
    qml.adjoint(qml.T)(wires = 0)
    qml.RZ(0.3,wires = 0)
    qml.adjoint(qml.S)(wires = 0)

    return qml.state()
many_rotations()

tensor([0.69916673-0.10566872j, 0.56910461-0.41966647j], requires_grad=True)

In [8]:
# 4
dev = qml.device('default.qubit', wires=3)

@qml.qnode(dev)
def too_many_ts():
    """You can implement the original circuit here as well, it may help you with
    testing to ensure that the circuits have the same effect.

    Returns:
        array[float]: The measurement outcome probabilities.
    """

    return qml.probs(wires=[0, 1, 2])

@qml.qnode(dev)
def just_enough_ts():
    """Implement an equivalent circuit as the above with the minimum number of 
    T and T^\dagger gates required.

    Returns:
        array[float]: The measurement outcome probabilities.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # IMPLEMENT THE CIRCUIT, BUT COMBINE AND OPTIMIZE THE GATES
    # TO MINIMIZE THE NUMBER OF TS
    qml.Hadamard(wires=0)
    qml.Hadamard(wires=1)
    qml.Hadamard(wires=2)
    qml.S(wires=0)
    qml.Hadamard(wires = 0)
    qml.adjoint(qml.S)(wires = 0)
    qml.Hadamard(wires=0)
    qml.T(wires=1)
    qml.Hadamard(wires=1)
    qml.PauliZ(wires=1)
    qml.Hadamard(wires=1)
    qml.adjoint(qml.T)(wires=2)
    qml.Hadamard(wires=2)
    qml.adjoint(qml.S)(wires=2)
    qml.adjoint(qml.T)(wires = 2)
    qml.Hadamard(wires=2)

    return qml.probs(wires=[0, 1, 2])

##################
# YOUR CODE HERE #
##################

# FILL IN THE CORRECT VALUES FOR THE ORIGINAL CIRCUIT
original_depth = 8
original_t_count = 13
original_t_depth = 6

# FILL IN THE CORRECT VALUES FOR THE NEW, OPTIMIZED CIRCUIT
optimal_depth = 6
optimal_t_count = 3
optimal_t_depth = 2
just_enough_ts()

tensor([0.   , 0.   , 0.   , 0.   , 0.375, 0.125, 0.375, 0.125], requires_grad=True)