# A First Taste

## States and Observations.

We calculate an expectations of any event $M$ that has take the values $\mu_1,\mu_2,..,\mu_k$ as


$$ \begin{equation}
\langle M \rangle = \sum_{i = 0}^k p_k\mu_k
\end{equation}
$$, where $p_k$ is the probabilites of each event.

In [8]:
import pennylane as qml
import numpy as np
events_names = ['event_1','event_2','event_3','event_4'] #events names are values of events_names_M
events_numbers = [1,2,3,4]
events_probabilites = [0.2,0.2,0.2,0.4]
events_dict = dict(zip(events_names,events_numbers))
events_probabilites_dict = dict(zip(events_names,events_probabilites))
expectations_of_event_M = np.sum([events_probabilites[index] * events_numbers[index] for index in range(len(events_names))])
print(expectations_of_event_M)

#The result of 2.8 indicates that Event_3 and Event 4 are most likely to contains the information about the quantum state.


2.8000000000000003


So far we have four events and their probabilties. Upon calculating the expectation value, we found that particle on this system is most likely to be contained toward right hand then the left hand side of the system. Dr. Schuld claims that upon calcuating the expected value, we need two steps to arrive at the quantum system with K different possible configuration, measurements or outcomes. Remember here, we are at a single system and we have the chance to get $K$ outcomes. However, it is not clear yet, if this $K$ is same as the number of events $k$. 
1. Rewrite the probabilites and the outcomes as matrices and vector.
$$ \begin{equation}
q = \begin{pmatrix} \sqrt{p_1} \\ . \\ . \\ \sqrt{p_k} \end{pmatrix} = \sqrt{p_1} \begin{pmatrix} 1 \\ 0 \\ . \\ . \\0 \end{pmatrix} + ..... +\sqrt{p_k} \begin{pmatrix} 0 \\ 0 \\ . \\ . \\1 \end{pmatrix}
\end{equation}
$$
2. Replace real positive probabilities with complex amplitudes.

In [9]:
# Lets do step 1. 
# Writing prpbabilites as vectors.
q = np.asarray([np.sqrt(p) for p in events_probabilites])

matrix_length = len(events_names)
M = np.zeros((matrix_length,matrix_length),float)
np.fill_diagonal(M,events_numbers)
print(M)



[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


We can redefine the Expected value of an event as,
$$
\begin{equation}
\langle M \rangle = q^T M q = \sum_{i = 0}^k p_k\mu_k
\end{equation}
$$
where $M$ is a diagonal matrix with q or $\mu_i$ value along its diagonal.

In [10]:
expected_value = np.dot(np.dot(q.T,M),q) #This is a vectorized version of the above equation, and it is much faster than the above equation.
print(expected_value)

2.8


Lets define a basis vector $(1,0,....,0)^T$ that forms a subspace of $\mathbb{R}^k$ that is associated with first event $event_1$.

In [11]:
basis_vec_of_first_event = np.asarray([1 if i == 0 else 0 for i in range(len(events_names))])
outer_product_of_a  = np.outer(basis_vec_of_first_event,basis_vec_of_first_event)
print(np.dot(basis_vec_of_first_event,q))


0.4472135954999579


### Eigenvalue and Eigen Vector

In [12]:
eigen_val,eigen_vec = np.linalg.eig(M)
print(f"Eigenvalues of M: {eigen_val}")
print(f"Eigenvectors of M: {eigen_vec}")

#Lets check for the equation, M*v = w*v
v1_1 = np.asarray([1 if i == 0 else 0 for i in range(len(events_names))])
v2_2 = np.asarray([1 if i == 1 else 0 for i in range(len(events_names))])
v3_3 = np.asarray([1 if i == 2 else 0 for i in range(len(events_names))])
v4_4 = np.asarray([1 if i == 3 else 0 for i in range(len(events_names))])
v1,v2,v3,v4 = eigen_vec
q1,q2,q3,q4 = q.copy()

Eigenvalues of M: [1. 2. 3. 4.]
Eigenvectors of M: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Above we define vectors $v1,..,v_k$ (for us k is 4), as an orthonormal eigenvectors of $M$. It fulfil $Mv_k  = \mu_k v_k$. \
We can define an amplitude vector $\alpha$ from $q$ such that 
$$
\langle M \rangle  = \alpha^{\dagger} M \alpha = \sum_{k = 1}^K | (v_k^{\dagger} \alpha )|^2 \mu_k
$$

In [13]:
l = np.dot(M,v1)
r = np.dot(events_numbers[0],v1)
a = np.asarray([np.sqrt(p) for p in events_probabilites],complex) #Complex amplitudes
M_via_v_and_mu = sum([np.dot(np.power(abs(np.dot(np.conj(eigen_vec[i]),a)),2),events_numbers[i]) for i in range(len(events_names))])
m_via_a = np.dot(np.dot(np.conj(a),M),a)
print(expectations_of_event_M,expected_value,M_via_v_and_mu,m_via_a)



2.8000000000000003 2.8 2.8 (2.8+0j)


Thus we have calculated an expected value using 4 methods.
1. $$ \begin{equation*} \langle M \rangle = \sum_{i = 0}^k p_k\mu_k,\text{ where $p_k$ is the probability of even $E_k$ and $\mu_k$ is an event value.}  \end{equation*} $$ 
2. $$ \begin{equation*} \langle M \rangle = q^T M q = \sum_{i = 0}^k p_k\mu_k \text{, where $q$ is a vector of $\sqrt{p_k}$ and $M$ is a diagonal matrix with $\mu_k$ on its diagonal.} \end{equation*} $$
3. $$\langle M \rangle  = \alpha^{\dagger} M \alpha \text{, where $\alpha$ is a complex vector of amplitudes. It is derived from $q$.}$$
4. $$\langle M \rangle  = \sum_{k = 1}^K | (v_k^{\dagger} \alpha )|^2 \mu_k \text{, where $v_i$ is an orthonormal eigen vectors of $M$.}$$


In [14]:
x = np.random.randn(2,1) #Get 10 random numbers from a normal distribution.
print(x)
k = np.sqrt(np.sum(x**2)) #Calculate the norm of the vector.
x_new = x/k #Normalize the vector.
sum([i**2 for i in x_new]) #Check that the norm is 1.


[[ 1.85663192]
 [-0.0713008 ]]


array([1.])

# 3.2 

## 3.2.2 Bits and Qubits


In [65]:
ket_0 = np.asarray([[1],[0]])
ket_1 = np.asarray([[0],[1]])
alpha_0 = 0.8 + 0.j
alpha_1 = 0.6 + 0.j
bra_0 = np.conj(ket_0).T
bra_1 = np.conj(ket_1).T
alpha = np.asarray([[alpha_0],[alpha_1]])
alpha_conj = np.conj(alpha).T



Geometric representation of a qubit.
$$
\ket{\psi} = e^{i \gamma}\big(cos\frac{\theta}{2} \ket{0} + e^{i \phi} sin\frac{\theta}{2}\ket{1}\big)
$$

In [89]:
def calculate_psi(gamma,psi,theta):
    state_ = np.exp(1j * gamma) * (np.cos(theta/2) * ket_0 + np.exp(1j * phi) * np.sin(theta/2) * ket_1)
    return state_

## Quantum Gates

In [102]:
X_gate = np.asarray([[0,1],[1,0]])
Y_gate = np.asarray([[0,-1j],[1j,0]])
Z_gate = np.asarray([[1,0],[0,-1]])
S_gate = np.asarray([[1,0],[0,1j]])
T_gate = np.asarray([[1,0],[0,np.exp(1j * np.pi/4)]])
Hadamard = np.asarray([[1/np.sqrt(2),1/np.sqrt(2)],[1/np.sqrt(2),-1/np.sqrt(2)]])
R = np.asarray([[1,0],[0,np.exp(-1j * np.pi/4)]])
CNOT = np.asarray([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
SWAP = np.asarray([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])
Toffoli = np.asarray([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],
                        [0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],
                        [0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])
Toffoli

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0]])